### PR TITLE
Medrano-Boogshh

### PR DESCRIPTION
**Pull request by kimmyyyy1**
Isang boogshh para sa lahat.

### CODE REVIEW

**Comment by Leekayle** [comment]
dunk it kim!

**Comment by LalanganRayAndre** [comment]
Hi! Its me RIANA NICOLE!

**Comment by jdarcega** [comment]
Hi Naksha

**Comment by MadelAmadeo** [comment]
Haiiiiwwww

**Comment by ERICA030** [comment]
PASABOGG KA KIM

**Pull request merged**
